export type Bison = {
  id: string;
  name: string;
  age: number;
  sex: "male" | "female";
  behavior: string;
  region: string;
  furLength: string;
  healthCondition: string;
  image: string;
  flock?: string;
  quarantine?: boolean;
};

export type Advert = {
  id: string;
  type: "offer" | "request";
  title: string;
  description: string;
  breeder: string;
  region?: string;
  behavior?: string;
  postedAt: string;
};

export const regions = [
  "Wielkopolska",
  "Podlasie",
  "Białowieża Forest",
  "Knyszyn Forest",
  "Borecka Forest",
  "Bieszczady",
  "Western Pomerania",
  "Near Gdańsk",
  "Lower Silesia",
  "Near Bałtów",
  "Augustów Forest",
  "Western Pomeranian Forests",
];

export const behaviors = [
  "calm",
  "passive",
  "playful",
  "aggressive",
  "very aggressive",
  "territorial",
  "curious",
  "lazy",
  "alert",
  "social",
  "dominant",
  "careful",
  "energetic",
  "loner",
  "cautious",
  "watchful",
];

export const healths = ["healthy", "injured"];

export const initialBisons: Bison[] = [
  {
    id: "1",
    name: "Pola",
    age: 14,
    sex: "female",
    behavior: "passive",
    region: "Wielkopolska",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/1.jpg",
  },
  {
    id: "2",
    name: "Polina",
    age: 8,
    sex: "female",
    behavior: "passive",
    region: "Podlasie",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/2.jpg",
  },
  {
    id: "3",
    name: "Polek",
    age: 12,
    sex: "male",
    behavior: "territorial",
    region: "Podlasie",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/3.jpg",
  },
  {
    id: "4",
    name: "Polikarp",
    age: 15,
    sex: "male",
    behavior: "passive",
    region: "Podlasie",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/4.jpg",
  },
  {
    id: "5",
    name: "Pomian",
    age: 13,
    sex: "male",
    behavior: "aggressive",
    region: "Western Pomerania",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/5.jpg",
  },
  {
    id: "6",
    name: "Pompejusz",
    age: 22,
    sex: "male",
    behavior: "aggressive",
    region: "Borecka Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/6.jpg",
  },
  {
    id: "7",
    name: "Polańka",
    age: 16,
    sex: "female",
    behavior: "passive",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/7.jpg",
  },
  {
    id: "8",
    name: "Polidora",
    age: 22,
    sex: "female",
    behavior: "passive",
    region: "Near Gdańsk",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/8.jpg",
  },
  {
    id: "9",
    name: "Porfir",
    age: 8,
    sex: "male",
    behavior: "territorial",
    region: "Bieszczady",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/9.jpg",
  },
  {
    id: "10",
    name: "Polesia",
    age: 15,
    sex: "female",
    behavior: "very aggressive",
    region: "Białowieża Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/10.jpg",
  },
  {
    id: "11",
    name: "Polonia",
    age: 7,
    sex: "female",
    behavior: "passive",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/11.jpg",
  },
  {
    id: "12",
    name: "Pompeja",
    age: 14,
    sex: "female",
    behavior: "territorial",
    region: "Białowieża Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/12.jpg",
  },
  {
    id: "13",
    name: "Polan",
    age: 10,
    sex: "male",
    behavior: "passive",
    region: "Lower Silesia",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/13.jpg",
  },
  {
    id: "14",
    name: "Polinka",
    age: 24,
    sex: "female",
    behavior: "aggressive",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/14.jpg",
  },
  {
    id: "15",
    name: "Polykarp",
    age: 15,
    sex: "male",
    behavior: "territorial",
    region: "Near Bałtów",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/15.jpg",
  },
  {
    id: "16",
    name: "Polaś",
    age: 13,
    sex: "male",
    behavior: "calm",
    region: "Białowieża Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/16.jpg",
  },
  {
    id: "17",
    name: "Polana",
    age: 10,
    sex: "female",
    behavior: "alert",
    region: "Bieszczady",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/17.jpg",
  },
  {
    id: "18",
    name: "Poncjusz",
    age: 15,
    sex: "male",
    behavior: "energetic",
    region: "Knyszyn Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/18.jpg",
  },
  {
    id: "19",
    name: "Polidora",
    age: 9,
    sex: "female",
    behavior: "calm",
    region: "Augustów Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/19.jpg",
  },
  {
    id: "20",
    name: "Polmir",
    age: 11,
    sex: "male",
    behavior: "curious",
    region: "Western Pomeranian Forests",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/20.jpg",
  },
  {
    id: "21",
    name: "Polenus",
    age: 7,
    sex: "male",
    behavior: "lazy",
    region: "Borecka Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/21.jpg",
  },
  {
    id: "22",
    name: "Polidar",
    age: 12,
    sex: "male",
    behavior: "dominant",
    region: "Białowieża Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/22.jpg",
  },
  {
    id: "23",
    name: "Polena",
    age: 9,
    sex: "female",
    behavior: "calm",
    region: "Bieszczady",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/23.jpg",
  },
  {
    id: "24",
    name: "Poloniusz",
    age: 14,
    sex: "male",
    behavior: "cautious",
    region: "Augustów Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/24.jpg",
  },
  {
    id: "25",
    name: "Polybiusz",
    age: 10,
    sex: "male",
    behavior: "energetic",
    region: "Knyszyn Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/25.jpg",
  },
  {
    id: "26",
    name: "Poloniusz",
    age: 14,
    sex: "male",
    behavior: "territorial",
    region: "Borecka Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/26.jpg",
  },
  {
    id: "27",
    name: "Polidor",
    age: 7,
    sex: "male",
    behavior: "watchful",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/27.jpg",
  },
  {
    id: "28",
    name: "Poletta",
    age: 13,
    sex: "female",
    behavior: "social",
    region: "Western Pomeranian Forests",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/28.jpg",
  },
  {
    id: "29",
    name: "Poliana",
    age: 6,
    sex: "female",
    behavior: "playful",
    region: "Białowieża Forest",
    furLength: "normal",
    healthCondition: "healthy",
    image: "/assets/29.jpg",
  },
  {
    id: "30",
    name: "Polonus",
    age: 11,
    sex: "male",
    behavior: "loner",
    region: "Augustów Forest",
    furLength: "thick",
    healthCondition: "healthy",
    image: "/assets/30.jpg",
  },
];

export const initialAdverts: Advert[] = [
  {
    id: "adv1",
    type: "offer",
    title: "High-quality hay for winter",
    description: "Freshly cut hay bales. Available in bulk for breeders.",
    breeder: "Green Pastures Farm",
    region: "Białowieża Forest",
    postedAt: "2025-09-01",
  },
  {
    id: "adv2",
    type: "request",
    title: "calm female wisent",
    description:
      "Preferably 3–5 years old, good health, from Podlasie region.",
    breeder: "Jan Kowalski",
    region: "Podlasie",
    behavior: "calm",
    postedAt: "2025-09-08",
  },
  {
    id: "adv3",
    type: "offer",
    title: "Wisent feeding troughs",
    description: "Strong wooden troughs, suitable for outdoor herds.",
    breeder: "WildCare Supplies",
    postedAt: "2025-09-10",
  },
];