export type Bison = {
  id: string;
  name: string;
  age: number;
  sex: "male" | "female";
  behavior: string;
  region: string;
  furLength: string;
  healthCondition: string;
  image: any; // teraz będzie to require(...)
  flock?: string;
  quarantine?: boolean;
  genotype: string;
};

export type Advert = {
  id: string;
  type: "offer" | "request";
  title: string;
  description: string;
  breeder: string;
  region?: string;
  behavior?: string;
  postedAt: string;
};

export const regions = [
  "Białowieża",
  "Niepołomice",
  "Bieszczady",
  "Muczne",
  "Pszczyna",
  "Borki",
  "Smardzewice",
  "Wigry",
  "Drawno",
  "Knyszyn",
  "Borecka Puszcza",
  "Bałtów",
];

export const behaviors = [
  "calm",
  "passive",
  "playful",
  "aggressive",
  "very aggressive",
  "territorial",
  "curious",
  "lazy",
  "alert",
  "social",
  "dominant",
  "careful",
  "energetic",
  "loner",
  "cautious",
  "watchful",
];

export const healths = ["healthy", "injured"];

// 🔽 mapowanie ID -> lokalny asset
export const bisonImages: Record<string, any> = {
  "1": require("@/assets/1.jpg"),
  "2": require("@/assets/2.jpg"),
  "3": require("@/assets/3.jpg"),
  "4": require("@/assets/4.jpg"),
  "5": require("@/assets/5.jpg"),
  "6": require("@/assets/6.jpg"),
  "7": require("@/assets/7.jpg"),
  "8": require("@/assets/8.jpg"),
  "9": require("@/assets/9.jpg"),
  "10": require("@/assets/10.jpg"),
  "11": require("@/assets/11.jpg"),
  "12": require("@/assets/12.jpg"),
  "13": require("@/assets/13.jpg"),
  "14": require("@/assets/18.jpg"),
  "15": require("@/assets/15.jpg"),
  "16": require("@/assets/16.jpg"),
  "17": require("@/assets/17.jpg"),
  "18": require("@/assets/14.jpg"),
  "19": require("@/assets/19.jpg"),
  "20": require("@/assets/20.jpg"),
  "21": require("@/assets/21.jpg"),
  "22": require("@/assets/22.jpg"),
  "23": require("@/assets/23.jpg"),
  "24": require("@/assets/24.jpg"),
  "25": require("@/assets/28.jpg"),
  "26": require("@/assets/26.jpg"),
  "27": require("@/assets/27.jpg"),
  "28": require("@/assets/25.jpg"),
  "29": require("@/assets/29.jpg"),
  "30": require("@/assets/30.jpg"),
};

export const initialBisons: Bison[] = [
  {
    id: "1",
    name: "Pola",
    age: 14,
    sex: "female",
    behavior: "passive",
    region: "Smardzewice",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHh",
    image: bisonImages["1"],
  },
  {
    id: "2",
    name: "Polina",
    age: 8,
    sex: "female",
    behavior: "passive",
    region: "Borki",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaaSsHH",
    image: bisonImages["2"],
  },
  {
    id: "3",
    name: "Polek",
    age: 12,
    sex: "male",
    behavior: "territorial",
    region: "Knyszyn",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAaSsHh",
    image: bisonImages["3"],
  },
  {
    id: "4",
    name: "Polikarp",
    age: 15,
    sex: "male",
    behavior: "passive",
    region: "Borki",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFaaSsHh",
    image: bisonImages["4"],
  },
  {
    id: "5",
    name: "Pomian",
    age: 13,
    sex: "male",
    behavior: "aggressive",
    region: "Drawno",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfAaSsHH",
    image: bisonImages["5"],
  },
  {
    id: "6",
    name: "Pompejusz",
    age: 22,
    sex: "male",
    behavior: "aggressive",
    region: "Borecka Puszcza",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAaSsHh",
    image: bisonImages["6"],
  },
  {
    id: "7",
    name: "Polańka",
    age: 16,
    sex: "female",
    behavior: "passive",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFaaSsHh",
    image: bisonImages["7"],
  },
  {
    id: "8",
    name: "Polidora",
    age: 22,
    sex: "female",
    behavior: "passive",
    region: "Wigry",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaaSsHH",
    image: bisonImages["8"],
  },
  {
    id: "9",
    name: "Porfir",
    age: 8,
    sex: "male",
    behavior: "territorial",
    region: "Muczne",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAaSsHh",
    image: bisonImages["9"],
  },
  {
    id: "10",
    name: "Polesia",
    age: 15,
    sex: "female",
    behavior: "very aggressive",
    region: "Białowieża",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAASsHh",
    image: bisonImages["10"],
  },
  {
    id: "11",
    name: "Polonia",
    age: 7,
    sex: "female",
    behavior: "passive",
    region: "Bieszczady",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFaaSsHH",
    image: bisonImages["11"],
  },
  {
    id: "12",
    name: "Pompeja",
    age: 14,
    sex: "female",
    behavior: "territorial",
    region: "Białowieża",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfAaSsHh",
    image: bisonImages["12"],
  },
  {
    id: "13",
    name: "Polan",
    age: 10,
    sex: "male",
    behavior: "passive",
    region: "Pszczyna",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHh",
    image: bisonImages["13"],
  },
  {
    id: "14",
    name: "Polinka",
    age: 24,
    sex: "female",
    behavior: "aggressive",
    region: "Muczne",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFAaSsHh",
    image: bisonImages["14"],
  },
  {
    id: "15",
    name: "Polykarp",
    age: 15,
    sex: "male",
    behavior: "territorial",
    region: "Bałtów",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAaSsHh",
    image: bisonImages["15"],
  },
  {
    id: "16",
    name: "Polaś",
    age: 13,
    sex: "male",
    behavior: "calm",
    region: "Białowieża",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHH",
    image: bisonImages["16"],
  },
  {
    id: "17",
    name: "Polana",
    age: 10,
    sex: "female",
    behavior: "alert",
    region: "Bieszczady",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHh",
    image: bisonImages["17"],
  },
  {
    id: "18",
    name: "Poncjusz",
    age: 15,
    sex: "male",
    behavior: "energetic",
    region: "Knyszyn",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSSHH",
    image: bisonImages["18"],
  },
  {
    id: "19",
    name: "Polidora",
    age: 9,
    sex: "female",
    behavior: "calm",
    region: "Wigry",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHh",
    image: bisonImages["19"],
  },
  {
    id: "20",
    name: "Polmir",
    age: 11,
    sex: "male",
    behavior: "curious",
    region: "Drawno",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaaSsHh",
    image: bisonImages["20"],
  },
  {
    id: "21",
    name: "Polenus",
    age: 7,
    sex: "male",
    behavior: "lazy",
    region: "Borecka Puszcza",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFaassHh",
    image: bisonImages["21"],
  },
  {
    id: "22",
    name: "Polidar",
    age: 12,
    sex: "male",
    behavior: "dominant",
    region: "Białowieża",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfAaSsHH",
    image: bisonImages["22"],
  },
  {
    id: "23",
    name: "Polena",
    age: 9,
    sex: "female",
    behavior: "calm",
    region: "Niepołomice",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSsHh",
    image: bisonImages["23"],
  },
  {
    id: "24",
    name: "Poloniusz",
    age: 14,
    sex: "male",
    behavior: "cautious",
    region: "Wigry",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaaSsHh",
    image: bisonImages["24"],
  },
  {
    id: "25",
    name: "Polybiusz",
    age: 10,
    sex: "female",
    behavior: "energetic",
    region: "Knyszyn",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FFaaSSHH",
    image: bisonImages["25"],
  },
  {
    id: "26",
    name: "Poloniusz",
    age: 14,
    sex: "male",
    behavior: "territorial",
    region: "Borecka Puszcza",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffAaSsHh",
    image: bisonImages["26"],
  },
  {
    id: "27",
    name: "Polidor",
    age: 7,
    sex: "male",
    behavior: "watchful",
    region: "Muczne",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaaSsHH",
    image: bisonImages["27"],
  },
  {
    id: "28",
    name: "Poletta",
    age: 13,
    sex: "female",
    behavior: "social",
    region: "Drawno",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSSHh",
    image: bisonImages["28"],
  },
  {
    id: "29",
    name: "Poliana",
    age: 6,
    sex: "female",
    behavior: "playful",
    region: "Białowieża",
    furLength: "normal",
    healthCondition: "healthy",
    genotype: "ffaaSSHH",
    image: bisonImages["29"],
  },
  {
    id: "30",
    name: "Polonus",
    age: 11,
    sex: "male",
    behavior: "loner",
    region: "Wigry",
    furLength: "thick",
    healthCondition: "healthy",
    genotype: "FfaassHh",
    image: bisonImages["30"],
  },
];

export const initialAdverts: Advert[] = [
  {
    id: "adv1",
    type: "offer",
    title: "High-quality hay for winter",
    description: "Freshly cut hay bales. Available in bulk for breeders.",
    breeder: "Green Pastures Farm",
    region: "Białowieża",
    postedAt: "2025-09-01",
  },
  {
    id: "adv2",
    type: "request",
    title: "calm female wisent",
    description:
      "Preferably 3–5 years old, good health, from Podlasie region.",
    breeder: "Jan Kowalski",
    region: "Borki",
    behavior: "calm",
    postedAt: "2025-09-08",
  },
  {
    id: "adv3",
    type: "offer",
    title: "Wisent feeding troughs",
    description: "Strong wooden troughs, suitable for outdoor herds.",
    breeder: "WildCare Supplies",
    postedAt: "2025-09-10",
  },
  {
    id: "adv4",
    type: "offer",
    title: "Young male bison for adoption",
    description:
      "2-year-old male bison, healthy and playful. Looking for a good home.",
    breeder: "Anna Nowak",
    region: "Niepołomice",
    behavior: "playful",
    postedAt: "2025-09-15",
  },
];